antho_webdesign/urls.py
from django.contrib import admin
from django.urls import path, include
from antho_webdesign import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', include('blog.urls')),
    path('', include('contact.urls')),
    # path('', include('for_test.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import PostDetail, PostList, index_test, index_blog, \
    DevActus, DevActusDetail, HackActus, CryptosActus, IaActus, DevActusTest, blog_category_list

urlpatterns = [
    path('blog/', index_blog, name="index_blog"),
    path('blog/test', index_test, name="index_test"),
    path('blog/list/', PostList.as_view(), name='list_post'),
    path('blog/list/categorie/', blog_category_list, name='blog_category_list'),
    path('blog/list/developpement/', DevActus.as_view(), name='list_post_dev'),
    path('blog/list/developpement/<slug:slug>/', DevActusDetail.as_view(), name='post_detail_dev'),

    path('blog/list/cybersecurite/', HackActus.as_view(), name='list_post_hack'),

    path('blog/list/cryptomonnaie/', CryptosActus.as_view(), name='list_post_cryptos'),

    path('blog/list/i-a/', IaActus.as_view(), name='list_post_ia'),

    path('blog/post_detail/<slug:slug>/', PostDetail.as_view(), name='post_detail'),

    path('blog/list/developpement/test', DevActusTest.as_view(), name='list_post_dev_test'),
]

for_test/urls.py
from django.urls import path

from for_test.views import CategoryList, ProjectWeb, ProjectWebDetail, details, details_projet

urlpatterns = [
    path('t/liste-categories/', CategoryList.as_view(), name="list_categories"),
    path('t/liste/', ProjectWeb.as_view(), name="projet_web"),
    path('t/list-projet-web/<str:slug>/', details_projet, name="details_projet"),  # list of projects web
    path('t/categories/<str:slug>/', ProjectWebDetail.as_view(), name='project_web_detail'),
    path('t/projet/<str:slug>/details', details, name='details'),
]

for_test/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    project_category = models.CharField(max_length=120, blank=True, null=True)
    category_name = models.CharField(max_length=120, blank=True, null=True)
    slug = models.SlugField(max_length=120, blank=True, null=True)
    image_cat = models.ImageField(upload_to='images/portfolio/category',
                                  default='images/portfolio/category/default.jpg')
    description_cat = models.TextField(max_length=2500, blank=True, null=True)

    def get_project_liste(self):
        return Project.objects.filter(category=self)

    def __str__(self):
        return self.category_name

    class Meta:
        ordering = ['category_name']
        verbose_name_plural = 'Categories'
        verbose_name = 'Categorie'

    def get_absolute_url(self):
        return reverse(Category, kwargs={"slug": self.slug})



# Create your models here.
CATEGORY_CHOICES = (
    ('site_web', 'Site Web'),
    ('appli_mobile', 'Appli Mobile'),
    ('appli_desktop', 'Appli Desktop'),
    ('other', 'Other'),
)

PROJECT_STATUS = (
    ('en_cours', 'En Cours'),
    ('en_ligne', 'En ligne'),
    ('canceled', 'Suspendu'),
)


class Project(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    date_created_on = models.DateTimeField(auto_now_add=True)
    project_status = models.CharField(choices=PROJECT_STATUS, default='en_cours', max_length=10)
    language_tags = models.CharField(max_length=50)
    project_thumbnail = models.ImageField(upload_to='images/portfolio/project/',
                                          default='images/portfolio/project/default.jpg')
    project_url = models.URLField(max_length=200, default='#')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='projects',
                                 blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Projects'
        verbose_name = 'Project'
        ordering = ['-date_created_on']

    def get_absolute_url(self):
        return reverse('project_web_detail', args=[self.slug])

for_test/views.py
from django.contrib.sites import requests
from django.shortcuts import render, get_object_or_404
from django.views import generic

from for_test.models import Project, Category


# fonction affiche les details du projet
class CategoryList(generic.ListView):
    model = Project
    queryset = Project.objects.all()
    template_name = 'forTest/list_category.html'


class ProjectWeb(generic.ListView):
    model = Project
    queryset = Project.objects.all()
    template_name = 'forTest/web/list_category_web.html'


class ProjectWebDetail(generic.DetailView):
    model = Project
    queryset = Project.objects.all()
    template_name = 'forTest/web/details_projet.html'


def details_projet(request, slug):
    details_project = get_object_or_404(Project, slug=slug)
    return render(request, 'forTest/web/details_projet.html', {'details_project': details_project})


def details(request, slug):
    project = get_object_or_404(Project, slug=slug)
    return render(request, 'forTest/web/details_projet.html', {'project': project})

for_test/templates/forTest/details_test.html
{% extends 'portfolio/base_pr.html' %}
{% load static %}

{% block content %}

    {% for project in project_list %}
        <div class="card">
            <div class="card__content">
                <h2>{{ project.title }}</h2>
                <img src="{{ project.image.url }}" alt="project image">
                <p>{{ project.description }}</p>
                <a href="{% url 'details_projet' project.slug %}">Voir le projet</a>
            </div>
        </div>
    {% endfor %}

{% endblock %}

for_test/templates/forTest/list_category.html
{% extends 'portfolio/base_pr.html' %}
{% load static %}

{% block content %}
    <!-- Boucle sur les projets -->
<style>

.card {
  display: flex;
  flex-direction: row;
  align-items: center;
}

.card__content {
  align-items: center;
  display: flex;
  flex-direction: column;
}

.title {
 text-align: center;
 margin: 80px auto;
}

</style>
    <div class="title">
        <h1>Liste de mes projetss</h1>
    </div>

    <div class="box">
        {% for category in project_list %}
                <div class="card">

                    <div class="card__content">
                        <h2 class="card__title animate text-dark text-bold">
                            <a href="javascript:" class="text-dark">{{ category.category.category_name }}</a>
                        </h2>
                        <p class="text-dark"> {{ category.category.description_cat }}</p>
                    </div>
                    <button class="card__btn">
                        <a href="{% url 'projet_web' %}"><!-- TODO : Lien vers la page liste site vitrine -->
                            <i class="fa fa-arrow-right fa-fw"></i>
                        </a>

                    </button>
                </div>
        {% endfor %}
    </div>
{% endblock %}